In [1]:
import pickle
from keras.models import Sequential
from keras.layers import Dense,Dropout, Activation,Flatten
from keras.layers import Conv2D, MaxPooling2D
import matplotlib.pyplot as plt
import numpy as np
from keras.utils import np_utils
from sklearn.model_selection import train_test_split

In [2]:
def loadPickleData(file):
    data = pickle.load(open(file, 'rb'));
    images = data[0];
    labels = data[1];
    return [images, labels]

In [3]:
[images,labels] = loadPickleData("./../Data/pickledFiles/Num_SingleDigit.p")

In [4]:
y = np_utils.to_categorical(labels);
print(y);
print(y.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
(2000, 10)


In [16]:
X = images

In [17]:
X.shape

(2000, 60, 40)

In [18]:
X = np.reshape(X, (2000,60,40,1))

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.1);

In [33]:
model = Sequential();


In [34]:
model.add(Conv2D(20,(2,2),strides = 1, activation = 'relu', input_shape = (60,40,1)))
model.add(MaxPooling2D(pool_size = (2,2)));

In [35]:
model.add(Conv2D(40,(3,3),strides = 1, activation = 'relu'))
model.add(Dropout(0.1));
model.add(Conv2D(80,(2,2),strides = 1, activation = 'relu'))

In [36]:
model.add(Conv2D(40,(2,2),strides = 1, activation = 'relu'))

In [37]:
model.add(MaxPooling2D(pool_size = (2,2)));

In [38]:
model.add(Flatten())

In [39]:
model.add(Dense(500, activation = 'relu'))
model.add(Dropout(0.1));
model.add(Dense(200, activation = 'relu'))
model.add(Dropout(0.1));

In [40]:
num_classes = y.shape[1]
model.add(Dense(num_classes, activation = 'softmax'));

In [41]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [42]:
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size=1000, epochs=500, verbose=1);

Epoch 1/500
2/2 [==============================] - 2s 558ms/step - loss: 59.7059 - accuracy: 0.0989 - val_loss: 57.3178 - val_accuracy: 0.0950
Epoch 2/500
2/2 [==============================] - 1s 442ms/step - loss: 61.7925 - accuracy: 0.1056 - val_loss: 11.8698 - val_accuracy: 0.1000
Epoch 3/500
2/2 [==============================] - 1s 436ms/step - loss: 18.0544 - accuracy: 0.1078 - val_loss: 4.2401 - val_accuracy: 0.0950
Epoch 4/500
2/2 [==============================] - 1s 445ms/step - loss: 6.3123 - accuracy: 0.0961 - val_loss: 2.5718 - val_accuracy: 0.0850
Epoch 5/500
2/2 [==============================] - 1s 446ms/step - loss: 3.0958 - accuracy: 0.1128 - val_loss: 2.9066 - val_accuracy: 0.0950
Epoch 6/500
2/2 [==============================] - 1s 449ms/step - loss: 2.7696 - accuracy: 0.1039 - val_loss: 2.3433 - val_accuracy: 0.0700
Epoch 7/500
2/2 [==============================] - 1s 435ms/step - loss: 2.4282 - accuracy: 0.1122 - val_loss: 2.2974 - val_accuracy: 0.1100
Epoch 8/

Epoch 59/500
2/2 [==============================] - 1s 446ms/step - loss: 2.3010 - accuracy: 0.1028 - val_loss: 2.3050 - val_accuracy: 0.1200
Epoch 60/500
2/2 [==============================] - 1s 432ms/step - loss: 2.2998 - accuracy: 0.1156 - val_loss: 2.3051 - val_accuracy: 0.1200
Epoch 61/500
2/2 [==============================] - 1s 440ms/step - loss: 2.3013 - accuracy: 0.1094 - val_loss: 2.3052 - val_accuracy: 0.1200
Epoch 62/500
2/2 [==============================] - 1s 426ms/step - loss: 2.3006 - accuracy: 0.1044 - val_loss: 2.3054 - val_accuracy: 0.1200
Epoch 63/500
2/2 [==============================] - 1s 436ms/step - loss: 2.3001 - accuracy: 0.1100 - val_loss: 2.3055 - val_accuracy: 0.1200
Epoch 64/500
2/2 [==============================] - 1s 437ms/step - loss: 2.3009 - accuracy: 0.1011 - val_loss: 2.3056 - val_accuracy: 0.1200
Epoch 65/500
2/2 [==============================] - 1s 422ms/step - loss: 2.3002 - accuracy: 0.0989 - val_loss: 2.3057 - val_accuracy: 0.1200
Epoch 

2/2 [==============================] - 1s 426ms/step - loss: 0.9443 - accuracy: 0.6817 - val_loss: 2.1321 - val_accuracy: 0.3300
Epoch 117/500
2/2 [==============================] - 1s 446ms/step - loss: 0.8854 - accuracy: 0.6922 - val_loss: 2.1840 - val_accuracy: 0.3650
Epoch 118/500
2/2 [==============================] - 1s 442ms/step - loss: 0.8261 - accuracy: 0.7250 - val_loss: 2.1882 - val_accuracy: 0.3800
Epoch 119/500
2/2 [==============================] - 1s 426ms/step - loss: 0.8015 - accuracy: 0.7261 - val_loss: 2.2293 - val_accuracy: 0.3550
Epoch 120/500
2/2 [==============================] - 1s 430ms/step - loss: 0.7384 - accuracy: 0.7444 - val_loss: 2.2423 - val_accuracy: 0.3750
Epoch 121/500
2/2 [==============================] - 1s 434ms/step - loss: 0.6972 - accuracy: 0.7628 - val_loss: 2.3620 - val_accuracy: 0.3600
Epoch 122/500
2/2 [==============================] - 1s 436ms/step - loss: 0.6464 - accuracy: 0.7811 - val_loss: 2.2442 - val_accuracy: 0.4050
Epoch 123/500

2/2 [==============================] - 1s 422ms/step - loss: 0.1040 - accuracy: 0.9667 - val_loss: 4.4581 - val_accuracy: 0.3550
Epoch 174/500
2/2 [==============================] - 1s 440ms/step - loss: 0.0934 - accuracy: 0.9739 - val_loss: 4.4600 - val_accuracy: 0.3550
Epoch 175/500
2/2 [==============================] - 1s 439ms/step - loss: 0.0969 - accuracy: 0.9678 - val_loss: 4.4423 - val_accuracy: 0.3400
Epoch 176/500
2/2 [==============================] - 1s 429ms/step - loss: 0.0863 - accuracy: 0.9739 - val_loss: 4.5561 - val_accuracy: 0.3550
Epoch 177/500
2/2 [==============================] - 1s 433ms/step - loss: 0.0840 - accuracy: 0.9744 - val_loss: 4.6050 - val_accuracy: 0.3600
Epoch 178/500
2/2 [==============================] - 1s 427ms/step - loss: 0.0982 - accuracy: 0.9711 - val_loss: 4.6551 - val_accuracy: 0.3450
Epoch 179/500
2/2 [==============================] - 1s 443ms/step - loss: 0.0797 - accuracy: 0.9778 - val_loss: 4.7325 - val_accuracy: 0.3300
Epoch 180/500

2/2 [==============================] - 1s 432ms/step - loss: 0.0406 - accuracy: 0.9856 - val_loss: 5.2221 - val_accuracy: 0.3350
Epoch 231/500
2/2 [==============================] - 1s 435ms/step - loss: 0.0443 - accuracy: 0.9833 - val_loss: 5.1720 - val_accuracy: 0.3450
Epoch 232/500
2/2 [==============================] - 1s 424ms/step - loss: 0.0613 - accuracy: 0.9822 - val_loss: 5.0362 - val_accuracy: 0.3750
Epoch 233/500
2/2 [==============================] - 1s 449ms/step - loss: 0.0437 - accuracy: 0.9856 - val_loss: 5.1138 - val_accuracy: 0.3750
Epoch 234/500
2/2 [==============================] - 1s 437ms/step - loss: 0.0451 - accuracy: 0.9839 - val_loss: 5.3132 - val_accuracy: 0.3600
Epoch 235/500
2/2 [==============================] - 1s 444ms/step - loss: 0.0339 - accuracy: 0.9889 - val_loss: 5.4680 - val_accuracy: 0.3600
Epoch 236/500
2/2 [==============================] - 1s 443ms/step - loss: 0.0358 - accuracy: 0.9867 - val_loss: 5.4834 - val_accuracy: 0.3650
Epoch 237/500

2/2 [==============================] - 1s 441ms/step - loss: 0.0200 - accuracy: 0.9950 - val_loss: 5.4775 - val_accuracy: 0.3450
Epoch 288/500
2/2 [==============================] - 1s 442ms/step - loss: 0.0308 - accuracy: 0.9917 - val_loss: 5.4080 - val_accuracy: 0.3600
Epoch 289/500
2/2 [==============================] - 1s 442ms/step - loss: 0.0407 - accuracy: 0.9872 - val_loss: 5.4912 - val_accuracy: 0.3500
Epoch 290/500
2/2 [==============================] - 1s 431ms/step - loss: 0.0360 - accuracy: 0.9906 - val_loss: 5.3909 - val_accuracy: 0.3500
Epoch 291/500
2/2 [==============================] - 1s 446ms/step - loss: 0.0248 - accuracy: 0.9928 - val_loss: 5.2059 - val_accuracy: 0.3700
Epoch 292/500
2/2 [==============================] - 1s 442ms/step - loss: 0.0316 - accuracy: 0.9917 - val_loss: 5.1400 - val_accuracy: 0.3750
Epoch 293/500
2/2 [==============================] - 1s 424ms/step - loss: 0.0207 - accuracy: 0.9944 - val_loss: 5.3784 - val_accuracy: 0.3400
Epoch 294/500

2/2 [==============================] - 1s 432ms/step - loss: 0.0193 - accuracy: 0.9933 - val_loss: 5.5017 - val_accuracy: 0.3150
Epoch 345/500
2/2 [==============================] - 1s 442ms/step - loss: 0.0210 - accuracy: 0.9928 - val_loss: 5.6454 - val_accuracy: 0.3350
Epoch 346/500
2/2 [==============================] - 1s 440ms/step - loss: 0.0129 - accuracy: 0.9956 - val_loss: 5.8123 - val_accuracy: 0.3300
Epoch 347/500
2/2 [==============================] - 1s 446ms/step - loss: 0.0132 - accuracy: 0.9978 - val_loss: 5.7836 - val_accuracy: 0.3300
Epoch 348/500
2/2 [==============================] - 1s 428ms/step - loss: 0.0096 - accuracy: 0.9972 - val_loss: 5.7376 - val_accuracy: 0.3550
Epoch 349/500
2/2 [==============================] - 1s 430ms/step - loss: 0.0160 - accuracy: 0.9944 - val_loss: 5.6340 - val_accuracy: 0.3600
Epoch 350/500
2/2 [==============================] - 1s 449ms/step - loss: 0.0188 - accuracy: 0.9933 - val_loss: 5.7850 - val_accuracy: 0.3650
Epoch 351/500

2/2 [==============================] - 1s 443ms/step - loss: 0.0188 - accuracy: 0.9939 - val_loss: 5.7865 - val_accuracy: 0.3750
Epoch 402/500
2/2 [==============================] - 1s 430ms/step - loss: 0.0114 - accuracy: 0.9961 - val_loss: 5.6521 - val_accuracy: 0.3850
Epoch 403/500
2/2 [==============================] - 1s 442ms/step - loss: 0.0138 - accuracy: 0.9956 - val_loss: 5.6340 - val_accuracy: 0.3900
Epoch 404/500
2/2 [==============================] - 1s 436ms/step - loss: 0.0186 - accuracy: 0.9944 - val_loss: 5.8035 - val_accuracy: 0.3800
Epoch 405/500
2/2 [==============================] - 1s 452ms/step - loss: 0.0235 - accuracy: 0.9956 - val_loss: 6.0099 - val_accuracy: 0.3600
Epoch 406/500
2/2 [==============================] - 1s 429ms/step - loss: 0.0107 - accuracy: 0.9956 - val_loss: 6.1394 - val_accuracy: 0.3750
Epoch 407/500
2/2 [==============================] - 1s 436ms/step - loss: 0.0178 - accuracy: 0.9922 - val_loss: 6.1544 - val_accuracy: 0.3600
Epoch 408/500

2/2 [==============================] - 1s 449ms/step - loss: 0.0114 - accuracy: 0.9961 - val_loss: 6.6487 - val_accuracy: 0.3600
Epoch 459/500
2/2 [==============================] - 1s 437ms/step - loss: 0.0198 - accuracy: 0.9928 - val_loss: 6.4284 - val_accuracy: 0.3400
Epoch 460/500
2/2 [==============================] - 1s 444ms/step - loss: 0.0109 - accuracy: 0.9967 - val_loss: 6.2710 - val_accuracy: 0.3350
Epoch 461/500
2/2 [==============================] - 1s 446ms/step - loss: 0.0134 - accuracy: 0.9967 - val_loss: 6.3119 - val_accuracy: 0.3550
Epoch 462/500
2/2 [==============================] - 1s 455ms/step - loss: 0.0096 - accuracy: 0.9972 - val_loss: 6.4699 - val_accuracy: 0.3600
Epoch 463/500
2/2 [==============================] - 1s 451ms/step - loss: 0.0117 - accuracy: 0.9983 - val_loss: 6.5165 - val_accuracy: 0.3650
Epoch 464/500
2/2 [==============================] - 1s 446ms/step - loss: 0.0138 - accuracy: 0.9944 - val_loss: 6.4454 - val_accuracy: 0.3600
Epoch 465/500

In [30]:
print(model.evaluate(X_test, y_test))

7/7 [==============================] - 0s 6ms/step - loss: 4.1219 - accuracy: 0.3800
[4.121947765350342, 0.3799999952316284]


In [49]:
max(history.history['val_accuracy'])

0.4050000011920929